# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Optional
from datetime import datetime

from pydantic import Field as FieldInfo

from ..._models import BaseModel

__all__ = ["NamedTransformation"]


class NamedTransformation(BaseModel):
    """
    A named transformation is an alias for a transformation string, letting you apply and later update complex transformations without changing your image or video URLs. Learn more about [named transformations](https://imagekit.io/docs/transformations#named-transformations).
    """

    id: Optional[str] = None
    """
    Unique identifier generated by ImageKit when the named transformation was
    created.
    """

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """ISO 8601 timestamp of when the named transformation was created."""

    enabled: Optional[bool] = None
    """Whether the named transformation is currently enabled."""

    name: Optional[str] = None
    """
    Name of the named transformation, used as `tr:n-<name>` in image and video URLs.
    """

    transformation: Optional[str] = None
    """Transformation string this name refers to.

    Always includes the `tr:` prefix, even if you omitted it in the request.
    """
