# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Optional
from datetime import datetime

from pydantic import Field as FieldInfo

from ..._models import BaseModel

__all__ = ["NamedTransformation"]


class NamedTransformation(BaseModel):
    """
    A named transformation is an alias for an actual transformation string, allowing you to apply and later update complex transformations without changing your image or video URLs. Learn more about [named transformations](https://imagekit.io/docs/transformations#named-transformations).
    """

    id: Optional[str] = None
    """Unique identifier of the named transformation.

    This is generated by ImageKit when you create a new named transformation.
    """

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp (ISO string) when the named transformation was created."""

    enabled: Optional[bool] = None
    """Whether this named transformation is currently enabled."""

    name: Optional[str] = None
    """
    Name of the named transformation, used as `tr:n-<name>` in image and video URLs.
    """

    transformation: Optional[str] = None
    """The transformation this name refers to.

    Always returned with the `tr:` prefix included, regardless of whether you
    supplied it when creating or updating the named transformation.
    """
