# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Union, Optional
from typing_extensions import Literal, Annotated, TypeAlias

from pydantic import Field as FieldInfo

from ..._utils import PropertyInfo
from ..._models import BaseModel

__all__ = ["URLEndpointResponse", "URLRewriter", "URLRewriterCloudinary", "URLRewriterImgix", "URLRewriterAkamai"]


class URLRewriterCloudinary(BaseModel):
    preserve_asset_delivery_types: bool = FieldInfo(alias="preserveAssetDeliveryTypes")
    """Whether to preserve `<asset_type>/<delivery_type>` in the rewritten URL."""

    type: Literal["CLOUDINARY"]


class URLRewriterImgix(BaseModel):
    type: Literal["IMGIX"]


class URLRewriterAkamai(BaseModel):
    type: Literal["AKAMAI"]


URLRewriter: TypeAlias = Annotated[
    Union[URLRewriterCloudinary, URLRewriterImgix, URLRewriterAkamai], PropertyInfo(discriminator="type")
]


class URLEndpointResponse(BaseModel):
    """URL‑endpoint object as returned by the API."""

    id: str
    """Unique identifier for the URL-endpoint.

    This is generated by ImageKit when you create a new URL-endpoint. For the
    default URL-endpoint, this is always `default`.
    """

    description: str
    """Description of the URL endpoint."""

    origins: List[str]
    """
    Ordered list of origin IDs to try when the file isn’t in the Media Library;
    ImageKit checks them in the sequence provided. Origin must be created before it
    can be used in a URL endpoint.
    """

    url_prefix: str = FieldInfo(alias="urlPrefix")
    """
    Path segment appended to your base URL to form the endpoint (letters, digits,
    and hyphens only — or empty for the default endpoint).
    """

    url_rewriter: Optional[URLRewriter] = FieldInfo(alias="urlRewriter", default=None)
    """Configuration for third-party URL rewriting."""
