# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

import os
from typing import Any, cast

import pytest

from imagekitio import ImageKit, AsyncImageKit
from imagekitio._utils import parse_datetime

base_url = os.environ.get("TEST_API_BASE_URL", "http://127.0.0.1:4010")


class TestDummy:
    parametrize = pytest.mark.parametrize("client", [False, True], indirect=True, ids=["loose", "strict"])

    @pytest.mark.skip(reason="Prism tests are disabled")
    @parametrize
    def test_method_create(self, client: ImageKit) -> None:
        dummy = client.dummy.create()
        assert dummy is None

    @pytest.mark.skip(reason="Prism tests are disabled")
    @parametrize
    def test_method_create_with_all_params(self, client: ImageKit) -> None:
        dummy = client.dummy.create(
            base_overlay={
                "layer_mode": "multiply",
                "position": {
                    "focus": "center",
                    "x": 0,
                    "y": 0,
                },
                "timing": {
                    "duration": 0,
                    "end": 0,
                    "start": 0,
                },
            },
            extension_config={
                "name": "remove-bg",
                "options": {
                    "add_shadow": True,
                    "bg_color": "bg_color",
                    "bg_image_url": "bg_image_url",
                    "semitransparency": True,
                },
            },
            extensions=[
                {
                    "name": "remove-bg",
                    "options": {
                        "add_shadow": True,
                        "bg_color": "bg_color",
                        "bg_image_url": "bg_image_url",
                        "semitransparency": True,
                    },
                },
                {
                    "max_tags": 5,
                    "min_confidence": 95,
                    "name": "google-auto-tagging",
                },
                {"name": "ai-auto-description"},
                {
                    "name": "ai-tasks",
                    "tasks": [
                        {
                            "instruction": "What types of clothing items are visible in this image?",
                            "type": "select_tags",
                            "max_selections": 1,
                            "min_selections": 0,
                            "vocabulary": ["shirt", "tshirt", "dress", "trousers", "jacket"],
                        },
                        {
                            "instruction": "Is this a luxury or high-end fashion item?",
                            "type": "yes_no",
                            "on_no": {
                                "add_tags": ["luxury", "premium"],
                                "remove_tags": ["budget", "affordable"],
                                "set_metadata": [
                                    {
                                        "field": "price_range",
                                        "value": "premium",
                                    }
                                ],
                                "unset_metadata": [{"field": "price_range"}],
                            },
                            "on_unknown": {
                                "add_tags": ["luxury", "premium"],
                                "remove_tags": ["budget", "affordable"],
                                "set_metadata": [
                                    {
                                        "field": "price_range",
                                        "value": "premium",
                                    }
                                ],
                                "unset_metadata": [{"field": "price_range"}],
                            },
                            "on_yes": {
                                "add_tags": ["luxury", "premium"],
                                "remove_tags": ["budget", "affordable"],
                                "set_metadata": [
                                    {
                                        "field": "price_range",
                                        "value": "premium",
                                    }
                                ],
                                "unset_metadata": [{"field": "price_range"}],
                            },
                        },
                    ],
                },
                {
                    "id": "ext_abc123",
                    "name": "saved-extension",
                },
            ],
            get_image_attributes_options={
                "src": "/my-image.jpg",
                "url_endpoint": "https://ik.imagekit.io/demo",
                "expires_in": 0,
                "query_parameters": {"foo": "string"},
                "signed": True,
                "transformation": [
                    {
                        "ai_change_background": "aiChangeBackground",
                        "ai_drop_shadow": True,
                        "ai_edit": "aiEdit",
                        "ai_remove_background": True,
                        "ai_remove_background_external": True,
                        "ai_retouch": True,
                        "ai_upscale": True,
                        "ai_variation": True,
                        "aspect_ratio": "4:3",
                        "audio_codec": "aac",
                        "background": "red",
                        "blur": 10,
                        "border": "5_FF0000",
                        "color_profile": True,
                        "color_replace": "colorReplace",
                        "contrast_stretch": True,
                        "crop": "force",
                        "crop_mode": "pad_resize",
                        "default_image": "defaultImage",
                        "distort": "distort",
                        "dpr": 2,
                        "duration": 0,
                        "end_offset": 0,
                        "flip": "h",
                        "focus": "center",
                        "format": "auto",
                        "gradient": True,
                        "grayscale": True,
                        "height": 200,
                        "lossless": True,
                        "metadata": True,
                        "named": "named",
                        "opacity": 0,
                        "original": True,
                        "overlay": {
                            "layer_mode": "multiply",
                            "position": {
                                "focus": "center",
                                "x": 0,
                                "y": 0,
                            },
                            "timing": {
                                "duration": 0,
                                "end": 0,
                                "start": 0,
                            },
                            "text": "text",
                            "type": "text",
                            "encoding": "auto",
                            "transformation": [
                                {
                                    "alpha": 1,
                                    "background": "background",
                                    "flip": "h",
                                    "font_color": "fontColor",
                                    "font_family": "fontFamily",
                                    "font_size": 0,
                                    "inner_alignment": "left",
                                    "line_height": 0,
                                    "padding": 0,
                                    "radius": 0,
                                    "rotation": 0,
                                    "typography": "typography",
                                    "width": 0,
                                }
                            ],
                        },
                        "page": 0,
                        "progressive": True,
                        "quality": 80,
                        "radius": 20,
                        "raw": "raw",
                        "rotation": 90,
                        "shadow": True,
                        "sharpen": True,
                        "start_offset": 0,
                        "streaming_resolutions": ["240"],
                        "trim": True,
                        "unsharp_mask": True,
                        "video_codec": "h264",
                        "width": 300,
                        "x": 0,
                        "x_center": 0,
                        "y": 0,
                        "y_center": 0,
                        "zoom": 0,
                    }
                ],
                "transformation_position": "path",
                "device_breakpoints": [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
                "image_breakpoints": [16, 32, 48, 64, 96, 128, 256, 384],
                "sizes": "(min-width: 768px) 50vw, 100vw",
                "width": 400,
            },
            image_overlay={
                "layer_mode": "multiply",
                "position": {
                    "focus": "center",
                    "x": 0,
                    "y": 0,
                },
                "timing": {
                    "duration": 0,
                    "end": 0,
                    "start": 0,
                },
                "input": "input",
                "type": "image",
                "encoding": "auto",
                "transformation": [
                    {
                        "ai_change_background": "aiChangeBackground",
                        "ai_drop_shadow": True,
                        "ai_edit": "aiEdit",
                        "ai_remove_background": True,
                        "ai_remove_background_external": True,
                        "ai_retouch": True,
                        "ai_upscale": True,
                        "ai_variation": True,
                        "aspect_ratio": "4:3",
                        "audio_codec": "aac",
                        "background": "red",
                        "blur": 10,
                        "border": "5_FF0000",
                        "color_profile": True,
                        "color_replace": "colorReplace",
                        "contrast_stretch": True,
                        "crop": "force",
                        "crop_mode": "pad_resize",
                        "default_image": "defaultImage",
                        "distort": "distort",
                        "dpr": 2,
                        "duration": 0,
                        "end_offset": 0,
                        "flip": "h",
                        "focus": "center",
                        "format": "auto",
                        "gradient": True,
                        "grayscale": True,
                        "height": 200,
                        "lossless": True,
                        "metadata": True,
                        "named": "named",
                        "opacity": 0,
                        "original": True,
                        "overlay": {
                            "layer_mode": "multiply",
                            "position": {
                                "focus": "center",
                                "x": 0,
                                "y": 0,
                            },
                            "timing": {
                                "duration": 0,
                                "end": 0,
                                "start": 0,
                            },
                            "text": "text",
                            "type": "text",
                            "encoding": "auto",
                            "transformation": [
                                {
                                    "alpha": 1,
                                    "background": "background",
                                    "flip": "h",
                                    "font_color": "fontColor",
                                    "font_family": "fontFamily",
                                    "font_size": 0,
                                    "inner_alignment": "left",
                                    "line_height": 0,
                                    "padding": 0,
                                    "radius": 0,
                                    "rotation": 0,
                                    "typography": "typography",
                                    "width": 0,
                                }
                            ],
                        },
                        "page": 0,
                        "progressive": True,
                        "quality": 80,
                        "radius": 20,
                        "raw": "raw",
                        "rotation": 90,
                        "shadow": True,
                        "sharpen": True,
                        "start_offset": 0,
                        "streaming_resolutions": ["240"],
                        "trim": True,
                        "unsharp_mask": True,
                        "video_codec": "h264",
                        "width": 300,
                        "x": 0,
                        "x_center": 0,
                        "y": 0,
                        "y_center": 0,
                        "zoom": 0,
                    }
                ],
            },
            overlay={
                "layer_mode": "multiply",
                "position": {
                    "focus": "center",
                    "x": 0,
                    "y": 0,
                },
                "timing": {
                    "duration": 0,
                    "end": 0,
                    "start": 0,
                },
                "text": "text",
                "type": "text",
                "encoding": "auto",
                "transformation": [
                    {
                        "alpha": 1,
                        "background": "background",
                        "flip": "h",
                        "font_color": "fontColor",
                        "font_family": "fontFamily",
                        "font_size": 0,
                        "inner_alignment": "left",
                        "line_height": 0,
                        "padding": 0,
                        "radius": 0,
                        "rotation": 0,
                        "typography": "typography",
                        "width": 0,
                    }
                ],
            },
            overlay_position={
                "focus": "center",
                "x": 0,
                "y": 0,
            },
            overlay_timing={
                "duration": 0,
                "end": 0,
                "start": 0,
            },
            responsive_image_attributes={
                "src": "https://ik.imagekit.io/demo/image.jpg?tr=w-3840",
                "sizes": "100vw",
                "src_set": "https://ik.imagekit.io/demo/image.jpg?tr=w-640 640w, https://ik.imagekit.io/demo/image.jpg?tr=w-1080 1080w, https://ik.imagekit.io/demo/image.jpg?tr=w-1920 1920w",
                "width": 400,
            },
            saved_extensions={
                "id": "ext_abc123",
                "config": {
                    "name": "remove-bg",
                    "options": {
                        "add_shadow": True,
                        "bg_color": "bg_color",
                        "bg_image_url": "bg_image_url",
                        "semitransparency": True,
                    },
                },
                "created_at": parse_datetime("2019-12-27T18:11:19.117Z"),
                "description": "Analyzes vehicle images for type, condition, and quality assessment",
                "name": "Car Quality Analysis",
                "updated_at": parse_datetime("2019-12-27T18:11:19.117Z"),
            },
            solid_color_overlay={
                "layer_mode": "multiply",
                "position": {
                    "focus": "center",
                    "x": 0,
                    "y": 0,
                },
                "timing": {
                    "duration": 0,
                    "end": 0,
                    "start": 0,
                },
                "color": "color",
                "type": "solidColor",
                "transformation": [
                    {
                        "alpha": 1,
                        "background": "background",
                        "gradient": True,
                        "height": 0,
                        "radius": 0,
                        "width": 0,
                    }
                ],
            },
            solid_color_overlay_transformation={
                "alpha": 1,
                "background": "background",
                "gradient": True,
                "height": 0,
                "radius": 0,
                "width": 0,
            },
            src_options={
                "src": "/my-image.jpg",
                "url_endpoint": "https://ik.imagekit.io/demo",
                "expires_in": 0,
                "query_parameters": {"foo": "string"},
                "signed": True,
                "transformation": [
                    {
                        "ai_change_background": "aiChangeBackground",
                        "ai_drop_shadow": True,
                        "ai_edit": "aiEdit",
                        "ai_remove_background": True,
                        "ai_remove_background_external": True,
                        "ai_retouch": True,
                        "ai_upscale": True,
                        "ai_variation": True,
                        "aspect_ratio": "4:3",
                        "audio_codec": "aac",
                        "background": "red",
                        "blur": 10,
                        "border": "5_FF0000",
                        "color_profile": True,
                        "color_replace": "colorReplace",
                        "contrast_stretch": True,
                        "crop": "force",
                        "crop_mode": "pad_resize",
                        "default_image": "defaultImage",
                        "distort": "distort",
                        "dpr": 2,
                        "duration": 0,
                        "end_offset": 0,
                        "flip": "h",
                        "focus": "center",
                        "format": "auto",
                        "gradient": True,
                        "grayscale": True,
                        "height": 200,
                        "lossless": True,
                        "metadata": True,
                        "named": "named",
                        "opacity": 0,
                        "original": True,
                        "overlay": {
                            "layer_mode": "multiply",
                            "position": {
                                "focus": "center",
                                "x": 0,
                                "y": 0,
                            },
                            "timing": {
                                "duration": 0,
                                "end": 0,
                                "start": 0,
                            },
                            "text": "text",
                            "type": "text",
                            "encoding": "auto",
                            "transformation": [
                                {
                                    "alpha": 1,
                                    "background": "background",
                                    "flip": "h",
                                    "font_color": "fontColor",
                                    "font_family": "fontFamily",
                                    "font_size": 0,
                                    "inner_alignment": "left",
                                    "line_height": 0,
                                    "padding": 0,
                                    "radius": 0,
                                    "rotation": 0,
                                    "typography": "typography",
                                    "width": 0,
                                }
                            ],
                        },
                        "page": 0,
                        "progressive": True,
                        "quality": 80,
                        "radius": 20,
                        "raw": "raw",
                        "rotation": 90,
                        "shadow": True,
                        "sharpen": True,
                        "start_offset": 0,
                        "streaming_resolutions": ["240"],
                        "trim": True,
                        "unsharp_mask": True,
                        "video_codec": "h264",
                        "width": 300,
                        "x": 0,
                        "x_center": 0,
                        "y": 0,
                        "y_center": 0,
                        "zoom": 0,
                    }
                ],
                "transformation_position": "path",
            },
            streaming_resolution="240",
            subtitle_overlay={
                "layer_mode": "multiply",
                "position": {
                    "focus": "center",
                    "x": 0,
                    "y": 0,
                },
                "timing": {
                    "duration": 0,
                    "end": 0,
                    "start": 0,
                },
                "input": "input",
                "type": "subtitle",
                "encoding": "auto",
                "transformation": [
                    {
                        "background": "background",
                        "color": "color",
                        "font_family": "fontFamily",
                        "font_outline": "fontOutline",
                        "font_shadow": "fontShadow",
                        "font_size": 0,
                        "typography": "b",
                    }
                ],
            },
            subtitle_overlay_transformation={
                "background": "background",
                "color": "color",
                "font_family": "fontFamily",
                "font_outline": "fontOutline",
                "font_shadow": "fontShadow",
                "font_size": 0,
                "typography": "b",
            },
            text_overlay={
                "layer_mode": "multiply",
                "position": {
                    "focus": "center",
                    "x": 0,
                    "y": 0,
                },
                "timing": {
                    "duration": 0,
                    "end": 0,
                    "start": 0,
                },
                "text": "text",
                "type": "text",
                "encoding": "auto",
                "transformation": [
                    {
                        "alpha": 1,
                        "background": "background",
                        "flip": "h",
                        "font_color": "fontColor",
                        "font_family": "fontFamily",
                        "font_size": 0,
                        "inner_alignment": "left",
                        "line_height": 0,
                        "padding": 0,
                        "radius": 0,
                        "rotation": 0,
                        "typography": "typography",
                        "width": 0,
                    }
                ],
            },
            text_overlay_transformation={
                "alpha": 1,
                "background": "background",
                "flip": "h",
                "font_color": "fontColor",
                "font_family": "fontFamily",
                "font_size": 0,
                "inner_alignment": "left",
                "line_height": 0,
                "padding": 0,
                "radius": 0,
                "rotation": 0,
                "typography": "typography",
                "width": 0,
            },
            transformation={
                "ai_change_background": "aiChangeBackground",
                "ai_drop_shadow": True,
                "ai_edit": "aiEdit",
                "ai_remove_background": True,
                "ai_remove_background_external": True,
                "ai_retouch": True,
                "ai_upscale": True,
                "ai_variation": True,
                "aspect_ratio": "4:3",
                "audio_codec": "aac",
                "background": "red",
                "blur": 10,
                "border": "5_FF0000",
                "color_profile": True,
                "color_replace": "colorReplace",
                "contrast_stretch": True,
                "crop": "force",
                "crop_mode": "pad_resize",
                "default_image": "defaultImage",
                "distort": "distort",
                "dpr": 2,
                "duration": 0,
                "end_offset": 0,
                "flip": "h",
                "focus": "center",
                "format": "auto",
                "gradient": True,
                "grayscale": True,
                "height": 200,
                "lossless": True,
                "metadata": True,
                "named": "named",
                "opacity": 0,
                "original": True,
                "overlay": {
                    "layer_mode": "multiply",
                    "position": {
                        "focus": "center",
                        "x": 0,
                        "y": 0,
                    },
                    "timing": {
                        "duration": 0,
                        "end": 0,
                        "start": 0,
                    },
                    "text": "text",
                    "type": "text",
                    "encoding": "auto",
                    "transformation": [
                        {
                            "alpha": 1,
                            "background": "background",
                            "flip": "h",
                            "font_color": "fontColor",
                            "font_family": "fontFamily",
                            "font_size": 0,
                            "inner_alignment": "left",
                            "line_height": 0,
                            "padding": 0,
                            "radius": 0,
                            "rotation": 0,
                            "typography": "typography",
                            "width": 0,
                        }
                    ],
                },
                "page": 0,
                "progressive": True,
                "quality": 80,
                "radius": 20,
                "raw": "raw",
                "rotation": 90,
                "shadow": True,
                "sharpen": True,
                "start_offset": 0,
                "streaming_resolutions": ["240"],
                "trim": True,
                "unsharp_mask": True,
                "video_codec": "h264",
                "width": 300,
                "x": 0,
                "x_center": 0,
                "y": 0,
                "y_center": 0,
                "zoom": 0,
            },
            transformation_position="path",
            video_overlay={
                "layer_mode": "multiply",
                "position": {
                    "focus": "center",
                    "x": 0,
                    "y": 0,
                },
                "timing": {
                    "duration": 0,
                    "end": 0,
                    "start": 0,
                },
                "input": "input",
                "type": "video",
                "encoding": "auto",
                "transformation": [
                    {
                        "ai_change_background": "aiChangeBackground",
                        "ai_drop_shadow": True,
                        "ai_edit": "aiEdit",
                        "ai_remove_background": True,
                        "ai_remove_background_external": True,
                        "ai_retouch": True,
                        "ai_upscale": True,
                        "ai_variation": True,
                        "aspect_ratio": "4:3",
                        "audio_codec": "aac",
                        "background": "red",
                        "blur": 10,
                        "border": "5_FF0000",
                        "color_profile": True,
                        "color_replace": "colorReplace",
                        "contrast_stretch": True,
                        "crop": "force",
                        "crop_mode": "pad_resize",
                        "default_image": "defaultImage",
                        "distort": "distort",
                        "dpr": 2,
                        "duration": 0,
                        "end_offset": 0,
                        "flip": "h",
                        "focus": "center",
                        "format": "auto",
                        "gradient": True,
                        "grayscale": True,
                        "height": 200,
                        "lossless": True,
                        "metadata": True,
                        "named": "named",
                        "opacity": 0,
                        "original": True,
                        "overlay": {
                            "layer_mode": "multiply",
                            "position": {
                                "focus": "center",
                                "x": 0,
                                "y": 0,
                            },
                            "timing": {
                                "duration": 0,
                                "end": 0,
                                "start": 0,
                            },
                            "text": "text",
                            "type": "text",
                            "encoding": "auto",
                            "transformation": [
                                {
                                    "alpha": 1,
                                    "background": "background",
                                    "flip": "h",
                                    "font_color": "fontColor",
                                    "font_family": "fontFamily",
                                    "font_size": 0,
                                    "inner_alignment": "left",
                                    "line_height": 0,
                                    "padding": 0,
                                    "radius": 0,
                                    "rotation": 0,
                                    "typography": "typography",
                                    "width": 0,
                                }
                            ],
                        },
                        "page": 0,
                        "progressive": True,
                        "quality": 80,
                        "radius": 20,
                        "raw": "raw",
                        "rotation": 90,
                        "shadow": True,
                        "sharpen": True,
                        "start_offset": 0,
                        "streaming_resolutions": ["240"],
                        "trim": True,
                        "unsharp_mask": True,
                        "video_codec": "h264",
                        "width": 300,
                        "x": 0,
                        "x_center": 0,
                        "y": 0,
                        "y_center": 0,
                        "zoom": 0,
                    }
                ],
            },
        )
        assert dummy is None

    @pytest.mark.skip(reason="Prism tests are disabled")
    @parametrize
    def test_raw_response_create(self, client: ImageKit) -> None:
        response = client.dummy.with_raw_response.create()

        assert response.is_closed is True
        assert response.http_request.headers.get("X-Stainless-Lang") == "python"
        dummy = response.parse()
        assert dummy is None

    @pytest.mark.skip(reason="Prism tests are disabled")
    @parametrize
    def test_streaming_response_create(self, client: ImageKit) -> None:
        with client.dummy.with_streaming_response.create() as response:
            assert not response.is_closed
            assert response.http_request.headers.get("X-Stainless-Lang") == "python"

            dummy = response.parse()
            assert dummy is None

        assert cast(Any, response.is_closed) is True


class TestAsyncDummy:
    parametrize = pytest.mark.parametrize(
        "async_client", [False, True, {"http_client": "aiohttp"}], indirect=True, ids=["loose", "strict", "aiohttp"]
    )

    @pytest.mark.skip(reason="Prism tests are disabled")
    @parametrize
    async def test_method_create(self, async_client: AsyncImageKit) -> None:
        dummy = await async_client.dummy.create()
        assert dummy is None

    @pytest.mark.skip(reason="Prism tests are disabled")
    @parametrize
    async def test_method_create_with_all_params(self, async_client: AsyncImageKit) -> None:
        dummy = await async_client.dummy.create(
            base_overlay={
                "layer_mode": "multiply",
                "position": {
                    "focus": "center",
                    "x": 0,
                    "y": 0,
                },
                "timing": {
                    "duration": 0,
                    "end": 0,
                    "start": 0,
                },
            },
            extension_config={
                "name": "remove-bg",
                "options": {
                    "add_shadow": True,
                    "bg_color": "bg_color",
                    "bg_image_url": "bg_image_url",
                    "semitransparency": True,
                },
            },
            extensions=[
                {
                    "name": "remove-bg",
                    "options": {
                        "add_shadow": True,
                        "bg_color": "bg_color",
                        "bg_image_url": "bg_image_url",
                        "semitransparency": True,
                    },
                },
                {
                    "max_tags": 5,
                    "min_confidence": 95,
                    "name": "google-auto-tagging",
                },
                {"name": "ai-auto-description"},
                {
                    "name": "ai-tasks",
                    "tasks": [
                        {
                            "instruction": "What types of clothing items are visible in this image?",
                            "type": "select_tags",
                            "max_selections": 1,
                            "min_selections": 0,
                            "vocabulary": ["shirt", "tshirt", "dress", "trousers", "jacket"],
                        },
                        {
                            "instruction": "Is this a luxury or high-end fashion item?",
                            "type": "yes_no",
                            "on_no": {
                                "add_tags": ["luxury", "premium"],
                                "remove_tags": ["budget", "affordable"],
                                "set_metadata": [
                                    {
                                        "field": "price_range",
                                        "value": "premium",
                                    }
                                ],
                                "unset_metadata": [{"field": "price_range"}],
                            },
                            "on_unknown": {
                                "add_tags": ["luxury", "premium"],
                                "remove_tags": ["budget", "affordable"],
                                "set_metadata": [
                                    {
                                        "field": "price_range",
                                        "value": "premium",
                                    }
                                ],
                                "unset_metadata": [{"field": "price_range"}],
                            },
                            "on_yes": {
                                "add_tags": ["luxury", "premium"],
                                "remove_tags": ["budget", "affordable"],
                                "set_metadata": [
                                    {
                                        "field": "price_range",
                                        "value": "premium",
                                    }
                                ],
                                "unset_metadata": [{"field": "price_range"}],
                            },
                        },
                    ],
                },
                {
                    "id": "ext_abc123",
                    "name": "saved-extension",
                },
            ],
            get_image_attributes_options={
                "src": "/my-image.jpg",
                "url_endpoint": "https://ik.imagekit.io/demo",
                "expires_in": 0,
                "query_parameters": {"foo": "string"},
                "signed": True,
                "transformation": [
                    {
                        "ai_change_background": "aiChangeBackground",
                        "ai_drop_shadow": True,
                        "ai_edit": "aiEdit",
                        "ai_remove_background": True,
                        "ai_remove_background_external": True,
                        "ai_retouch": True,
                        "ai_upscale": True,
                        "ai_variation": True,
                        "aspect_ratio": "4:3",
                        "audio_codec": "aac",
                        "background": "red",
                        "blur": 10,
                        "border": "5_FF0000",
                        "color_profile": True,
                        "color_replace": "colorReplace",
                        "contrast_stretch": True,
                        "crop": "force",
                        "crop_mode": "pad_resize",
                        "default_image": "defaultImage",
                        "distort": "distort",
                        "dpr": 2,
                        "duration": 0,
                        "end_offset": 0,
                        "flip": "h",
                        "focus": "center",
                        "format": "auto",
                        "gradient": True,
                        "grayscale": True,
                        "height": 200,
                        "lossless": True,
                        "metadata": True,
                        "named": "named",
                        "opacity": 0,
                        "original": True,
                        "overlay": {
                            "layer_mode": "multiply",
                            "position": {
                                "focus": "center",
                                "x": 0,
                                "y": 0,
                            },
                            "timing": {
                                "duration": 0,
                                "end": 0,
                                "start": 0,
                            },
                            "text": "text",
                            "type": "text",
                            "encoding": "auto",
                            "transformation": [
                                {
                                    "alpha": 1,
                                    "background": "background",
                                    "flip": "h",
                                    "font_color": "fontColor",
                                    "font_family": "fontFamily",
                                    "font_size": 0,
                                    "inner_alignment": "left",
                                    "line_height": 0,
                                    "padding": 0,
                                    "radius": 0,
                                    "rotation": 0,
                                    "typography": "typography",
                                    "width": 0,
                                }
                            ],
                        },
                        "page": 0,
                        "progressive": True,
                        "quality": 80,
                        "radius": 20,
                        "raw": "raw",
                        "rotation": 90,
                        "shadow": True,
                        "sharpen": True,
                        "start_offset": 0,
                        "streaming_resolutions": ["240"],
                        "trim": True,
                        "unsharp_mask": True,
                        "video_codec": "h264",
                        "width": 300,
                        "x": 0,
                        "x_center": 0,
                        "y": 0,
                        "y_center": 0,
                        "zoom": 0,
                    }
                ],
                "transformation_position": "path",
                "device_breakpoints": [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
                "image_breakpoints": [16, 32, 48, 64, 96, 128, 256, 384],
                "sizes": "(min-width: 768px) 50vw, 100vw",
                "width": 400,
            },
            image_overlay={
                "layer_mode": "multiply",
                "position": {
                    "focus": "center",
                    "x": 0,
                    "y": 0,
                },
                "timing": {
                    "duration": 0,
                    "end": 0,
                    "start": 0,
                },
                "input": "input",
                "type": "image",
                "encoding": "auto",
                "transformation": [
                    {
                        "ai_change_background": "aiChangeBackground",
                        "ai_drop_shadow": True,
                        "ai_edit": "aiEdit",
                        "ai_remove_background": True,
                        "ai_remove_background_external": True,
                        "ai_retouch": True,
                        "ai_upscale": True,
                        "ai_variation": True,
                        "aspect_ratio": "4:3",
                        "audio_codec": "aac",
                        "background": "red",
                        "blur": 10,
                        "border": "5_FF0000",
                        "color_profile": True,
                        "color_replace": "colorReplace",
                        "contrast_stretch": True,
                        "crop": "force",
                        "crop_mode": "pad_resize",
                        "default_image": "defaultImage",
                        "distort": "distort",
                        "dpr": 2,
                        "duration": 0,
                        "end_offset": 0,
                        "flip": "h",
                        "focus": "center",
                        "format": "auto",
                        "gradient": True,
                        "grayscale": True,
                        "height": 200,
                        "lossless": True,
                        "metadata": True,
                        "named": "named",
                        "opacity": 0,
                        "original": True,
                        "overlay": {
                            "layer_mode": "multiply",
                            "position": {
                                "focus": "center",
                                "x": 0,
                                "y": 0,
                            },
                            "timing": {
                                "duration": 0,
                                "end": 0,
                                "start": 0,
                            },
                            "text": "text",
                            "type": "text",
                            "encoding": "auto",
                            "transformation": [
                                {
                                    "alpha": 1,
                                    "background": "background",
                                    "flip": "h",
                                    "font_color": "fontColor",
                                    "font_family": "fontFamily",
                                    "font_size": 0,
                                    "inner_alignment": "left",
                                    "line_height": 0,
                                    "padding": 0,
                                    "radius": 0,
                                    "rotation": 0,
                                    "typography": "typography",
                                    "width": 0,
                                }
                            ],
                        },
                        "page": 0,
                        "progressive": True,
                        "quality": 80,
                        "radius": 20,
                        "raw": "raw",
                        "rotation": 90,
                        "shadow": True,
                        "sharpen": True,
                        "start_offset": 0,
                        "streaming_resolutions": ["240"],
                        "trim": True,
                        "unsharp_mask": True,
                        "video_codec": "h264",
                        "width": 300,
                        "x": 0,
                        "x_center": 0,
                        "y": 0,
                        "y_center": 0,
                        "zoom": 0,
                    }
                ],
            },
            overlay={
                "layer_mode": "multiply",
                "position": {
                    "focus": "center",
                    "x": 0,
                    "y": 0,
                },
                "timing": {
                    "duration": 0,
                    "end": 0,
                    "start": 0,
                },
                "text": "text",
                "type": "text",
                "encoding": "auto",
                "transformation": [
                    {
                        "alpha": 1,
                        "background": "background",
                        "flip": "h",
                        "font_color": "fontColor",
                        "font_family": "fontFamily",
                        "font_size": 0,
                        "inner_alignment": "left",
                        "line_height": 0,
                        "padding": 0,
                        "radius": 0,
                        "rotation": 0,
                        "typography": "typography",
                        "width": 0,
                    }
                ],
            },
            overlay_position={
                "focus": "center",
                "x": 0,
                "y": 0,
            },
            overlay_timing={
                "duration": 0,
                "end": 0,
                "start": 0,
            },
            responsive_image_attributes={
                "src": "https://ik.imagekit.io/demo/image.jpg?tr=w-3840",
                "sizes": "100vw",
                "src_set": "https://ik.imagekit.io/demo/image.jpg?tr=w-640 640w, https://ik.imagekit.io/demo/image.jpg?tr=w-1080 1080w, https://ik.imagekit.io/demo/image.jpg?tr=w-1920 1920w",
                "width": 400,
            },
            saved_extensions={
                "id": "ext_abc123",
                "config": {
                    "name": "remove-bg",
                    "options": {
                        "add_shadow": True,
                        "bg_color": "bg_color",
                        "bg_image_url": "bg_image_url",
                        "semitransparency": True,
                    },
                },
                "created_at": parse_datetime("2019-12-27T18:11:19.117Z"),
                "description": "Analyzes vehicle images for type, condition, and quality assessment",
                "name": "Car Quality Analysis",
                "updated_at": parse_datetime("2019-12-27T18:11:19.117Z"),
            },
            solid_color_overlay={
                "layer_mode": "multiply",
                "position": {
                    "focus": "center",
                    "x": 0,
                    "y": 0,
                },
                "timing": {
                    "duration": 0,
                    "end": 0,
                    "start": 0,
                },
                "color": "color",
                "type": "solidColor",
                "transformation": [
                    {
                        "alpha": 1,
                        "background": "background",
                        "gradient": True,
                        "height": 0,
                        "radius": 0,
                        "width": 0,
                    }
                ],
            },
            solid_color_overlay_transformation={
                "alpha": 1,
                "background": "background",
                "gradient": True,
                "height": 0,
                "radius": 0,
                "width": 0,
            },
            src_options={
                "src": "/my-image.jpg",
                "url_endpoint": "https://ik.imagekit.io/demo",
                "expires_in": 0,
                "query_parameters": {"foo": "string"},
                "signed": True,
                "transformation": [
                    {
                        "ai_change_background": "aiChangeBackground",
                        "ai_drop_shadow": True,
                        "ai_edit": "aiEdit",
                        "ai_remove_background": True,
                        "ai_remove_background_external": True,
                        "ai_retouch": True,
                        "ai_upscale": True,
                        "ai_variation": True,
                        "aspect_ratio": "4:3",
                        "audio_codec": "aac",
                        "background": "red",
                        "blur": 10,
                        "border": "5_FF0000",
                        "color_profile": True,
                        "color_replace": "colorReplace",
                        "contrast_stretch": True,
                        "crop": "force",
                        "crop_mode": "pad_resize",
                        "default_image": "defaultImage",
                        "distort": "distort",
                        "dpr": 2,
                        "duration": 0,
                        "end_offset": 0,
                        "flip": "h",
                        "focus": "center",
                        "format": "auto",
                        "gradient": True,
                        "grayscale": True,
                        "height": 200,
                        "lossless": True,
                        "metadata": True,
                        "named": "named",
                        "opacity": 0,
                        "original": True,
                        "overlay": {
                            "layer_mode": "multiply",
                            "position": {
                                "focus": "center",
                                "x": 0,
                                "y": 0,
                            },
                            "timing": {
                                "duration": 0,
                                "end": 0,
                                "start": 0,
                            },
                            "text": "text",
                            "type": "text",
                            "encoding": "auto",
                            "transformation": [
                                {
                                    "alpha": 1,
                                    "background": "background",
                                    "flip": "h",
                                    "font_color": "fontColor",
                                    "font_family": "fontFamily",
                                    "font_size": 0,
                                    "inner_alignment": "left",
                                    "line_height": 0,
                                    "padding": 0,
                                    "radius": 0,
                                    "rotation": 0,
                                    "typography": "typography",
                                    "width": 0,
                                }
                            ],
                        },
                        "page": 0,
                        "progressive": True,
                        "quality": 80,
                        "radius": 20,
                        "raw": "raw",
                        "rotation": 90,
                        "shadow": True,
                        "sharpen": True,
                        "start_offset": 0,
                        "streaming_resolutions": ["240"],
                        "trim": True,
                        "unsharp_mask": True,
                        "video_codec": "h264",
                        "width": 300,
                        "x": 0,
                        "x_center": 0,
                        "y": 0,
                        "y_center": 0,
                        "zoom": 0,
                    }
                ],
                "transformation_position": "path",
            },
            streaming_resolution="240",
            subtitle_overlay={
                "layer_mode": "multiply",
                "position": {
                    "focus": "center",
                    "x": 0,
                    "y": 0,
                },
                "timing": {
                    "duration": 0,
                    "end": 0,
                    "start": 0,
                },
                "input": "input",
                "type": "subtitle",
                "encoding": "auto",
                "transformation": [
                    {
                        "background": "background",
                        "color": "color",
                        "font_family": "fontFamily",
                        "font_outline": "fontOutline",
                        "font_shadow": "fontShadow",
                        "font_size": 0,
                        "typography": "b",
                    }
                ],
            },
            subtitle_overlay_transformation={
                "background": "background",
                "color": "color",
                "font_family": "fontFamily",
                "font_outline": "fontOutline",
                "font_shadow": "fontShadow",
                "font_size": 0,
                "typography": "b",
            },
            text_overlay={
                "layer_mode": "multiply",
                "position": {
                    "focus": "center",
                    "x": 0,
                    "y": 0,
                },
                "timing": {
                    "duration": 0,
                    "end": 0,
                    "start": 0,
                },
                "text": "text",
                "type": "text",
                "encoding": "auto",
                "transformation": [
                    {
                        "alpha": 1,
                        "background": "background",
                        "flip": "h",
                        "font_color": "fontColor",
                        "font_family": "fontFamily",
                        "font_size": 0,
                        "inner_alignment": "left",
                        "line_height": 0,
                        "padding": 0,
                        "radius": 0,
                        "rotation": 0,
                        "typography": "typography",
                        "width": 0,
                    }
                ],
            },
            text_overlay_transformation={
                "alpha": 1,
                "background": "background",
                "flip": "h",
                "font_color": "fontColor",
                "font_family": "fontFamily",
                "font_size": 0,
                "inner_alignment": "left",
                "line_height": 0,
                "padding": 0,
                "radius": 0,
                "rotation": 0,
                "typography": "typography",
                "width": 0,
            },
            transformation={
                "ai_change_background": "aiChangeBackground",
                "ai_drop_shadow": True,
                "ai_edit": "aiEdit",
                "ai_remove_background": True,
                "ai_remove_background_external": True,
                "ai_retouch": True,
                "ai_upscale": True,
                "ai_variation": True,
                "aspect_ratio": "4:3",
                "audio_codec": "aac",
                "background": "red",
                "blur": 10,
                "border": "5_FF0000",
                "color_profile": True,
                "color_replace": "colorReplace",
                "contrast_stretch": True,
                "crop": "force",
                "crop_mode": "pad_resize",
                "default_image": "defaultImage",
                "distort": "distort",
                "dpr": 2,
                "duration": 0,
                "end_offset": 0,
                "flip": "h",
                "focus": "center",
                "format": "auto",
                "gradient": True,
                "grayscale": True,
                "height": 200,
                "lossless": True,
                "metadata": True,
                "named": "named",
                "opacity": 0,
                "original": True,
                "overlay": {
                    "layer_mode": "multiply",
                    "position": {
                        "focus": "center",
                        "x": 0,
                        "y": 0,
                    },
                    "timing": {
                        "duration": 0,
                        "end": 0,
                        "start": 0,
                    },
                    "text": "text",
                    "type": "text",
                    "encoding": "auto",
                    "transformation": [
                        {
                            "alpha": 1,
                            "background": "background",
                            "flip": "h",
                            "font_color": "fontColor",
                            "font_family": "fontFamily",
                            "font_size": 0,
                            "inner_alignment": "left",
                            "line_height": 0,
                            "padding": 0,
                            "radius": 0,
                            "rotation": 0,
                            "typography": "typography",
                            "width": 0,
                        }
                    ],
                },
                "page": 0,
                "progressive": True,
                "quality": 80,
                "radius": 20,
                "raw": "raw",
                "rotation": 90,
                "shadow": True,
                "sharpen": True,
                "start_offset": 0,
                "streaming_resolutions": ["240"],
                "trim": True,
                "unsharp_mask": True,
                "video_codec": "h264",
                "width": 300,
                "x": 0,
                "x_center": 0,
                "y": 0,
                "y_center": 0,
                "zoom": 0,
            },
            transformation_position="path",
            video_overlay={
                "layer_mode": "multiply",
                "position": {
                    "focus": "center",
                    "x": 0,
                    "y": 0,
                },
                "timing": {
                    "duration": 0,
                    "end": 0,
                    "start": 0,
                },
                "input": "input",
                "type": "video",
                "encoding": "auto",
                "transformation": [
                    {
                        "ai_change_background": "aiChangeBackground",
                        "ai_drop_shadow": True,
                        "ai_edit": "aiEdit",
                        "ai_remove_background": True,
                        "ai_remove_background_external": True,
                        "ai_retouch": True,
                        "ai_upscale": True,
                        "ai_variation": True,
                        "aspect_ratio": "4:3",
                        "audio_codec": "aac",
                        "background": "red",
                        "blur": 10,
                        "border": "5_FF0000",
                        "color_profile": True,
                        "color_replace": "colorReplace",
                        "contrast_stretch": True,
                        "crop": "force",
                        "crop_mode": "pad_resize",
                        "default_image": "defaultImage",
                        "distort": "distort",
                        "dpr": 2,
                        "duration": 0,
                        "end_offset": 0,
                        "flip": "h",
                        "focus": "center",
                        "format": "auto",
                        "gradient": True,
                        "grayscale": True,
                        "height": 200,
                        "lossless": True,
                        "metadata": True,
                        "named": "named",
                        "opacity": 0,
                        "original": True,
                        "overlay": {
                            "layer_mode": "multiply",
                            "position": {
                                "focus": "center",
                                "x": 0,
                                "y": 0,
                            },
                            "timing": {
                                "duration": 0,
                                "end": 0,
                                "start": 0,
                            },
                            "text": "text",
                            "type": "text",
                            "encoding": "auto",
                            "transformation": [
                                {
                                    "alpha": 1,
                                    "background": "background",
                                    "flip": "h",
                                    "font_color": "fontColor",
                                    "font_family": "fontFamily",
                                    "font_size": 0,
                                    "inner_alignment": "left",
                                    "line_height": 0,
                                    "padding": 0,
                                    "radius": 0,
                                    "rotation": 0,
                                    "typography": "typography",
                                    "width": 0,
                                }
                            ],
                        },
                        "page": 0,
                        "progressive": True,
                        "quality": 80,
                        "radius": 20,
                        "raw": "raw",
                        "rotation": 90,
                        "shadow": True,
                        "sharpen": True,
                        "start_offset": 0,
                        "streaming_resolutions": ["240"],
                        "trim": True,
                        "unsharp_mask": True,
                        "video_codec": "h264",
                        "width": 300,
                        "x": 0,
                        "x_center": 0,
                        "y": 0,
                        "y_center": 0,
                        "zoom": 0,
                    }
                ],
            },
        )
        assert dummy is None

    @pytest.mark.skip(reason="Prism tests are disabled")
    @parametrize
    async def test_raw_response_create(self, async_client: AsyncImageKit) -> None:
        response = await async_client.dummy.with_raw_response.create()

        assert response.is_closed is True
        assert response.http_request.headers.get("X-Stainless-Lang") == "python"
        dummy = await response.parse()
        assert dummy is None

    @pytest.mark.skip(reason="Prism tests are disabled")
    @parametrize
    async def test_streaming_response_create(self, async_client: AsyncImageKit) -> None:
        async with async_client.dummy.with_streaming_response.create() as response:
            assert not response.is_closed
            assert response.http_request.headers.get("X-Stainless-Lang") == "python"

            dummy = await response.parse()
            assert dummy is None

        assert cast(Any, response.is_closed) is True
