# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Union, Optional
from typing_extensions import Literal, Annotated, TypeAlias

from pydantic import Field as FieldInfo

from ..._utils import PropertyInfo
from ..._models import BaseModel

__all__ = [
    "OriginResponse",
    "S3",
    "S3Compatible",
    "CloudinaryBackup",
    "WebFolder",
    "WebProxy",
    "Gcs",
    "AzureBlob",
    "AkeneoPim",
]


class S3(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    bucket: str
    """S3 bucket name."""

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    prefix: str
    """Path prefix inside the bucket."""

    type: Literal["S3"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


class S3Compatible(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    bucket: str
    """S3 bucket name."""

    endpoint: str
    """Custom S3-compatible endpoint."""

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    prefix: str
    """Path prefix inside the bucket."""

    s3_force_path_style: bool = FieldInfo(alias="s3ForcePathStyle")
    """Use path-style S3 URLs?"""

    type: Literal["S3_COMPATIBLE"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


class CloudinaryBackup(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    bucket: str
    """S3 bucket name."""

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    prefix: str
    """Path prefix inside the bucket."""

    type: Literal["CLOUDINARY_BACKUP"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


class WebFolder(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    base_url: str = FieldInfo(alias="baseUrl")
    """Root URL for the web folder origin."""

    forward_host_header_to_origin: bool = FieldInfo(alias="forwardHostHeaderToOrigin")
    """Forward the Host header to origin?"""

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    type: Literal["WEB_FOLDER"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


class WebProxy(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    type: Literal["WEB_PROXY"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


class Gcs(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    bucket: str

    client_email: str = FieldInfo(alias="clientEmail")

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    prefix: str

    type: Literal["GCS"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


class AzureBlob(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    account_name: str = FieldInfo(alias="accountName")

    container: str

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    prefix: str

    type: Literal["AZURE_BLOB"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


class AkeneoPim(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    base_url: str = FieldInfo(alias="baseUrl")
    """Akeneo instance base URL."""

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    type: Literal["AKENEO_PIM"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


OriginResponse: TypeAlias = Annotated[
    Union[S3, S3Compatible, CloudinaryBackup, WebFolder, WebProxy, Gcs, AzureBlob, AkeneoPim],
    PropertyInfo(discriminator="type"),
]
