# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Union, Optional
from typing_extensions import Literal, TypeAlias

from pydantic import Field as FieldInfo

from ..._models import BaseModel

__all__ = [
    "OriginListResponse",
    "OriginListResponseItem",
    "OriginListResponseItemS3",
    "OriginListResponseItemS3Compatible",
    "OriginListResponseItemCloudinaryBackup",
    "OriginListResponseItemWebFolder",
    "OriginListResponseItemWebProxy",
    "OriginListResponseItemGoogleCloudStorageGcs",
    "OriginListResponseItemAzureBlobStorage",
    "OriginListResponseItemAkeneoPim",
]


class OriginListResponseItemS3(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    bucket: str
    """S3 bucket name."""

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    prefix: object
    """Path prefix inside the bucket."""

    type: Literal["S3"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


class OriginListResponseItemS3Compatible(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    bucket: str
    """S3 bucket name."""

    endpoint: str
    """Custom S3-compatible endpoint."""

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    prefix: object
    """Path prefix inside the bucket."""

    s3_force_path_style: bool = FieldInfo(alias="s3ForcePathStyle")
    """Use path-style S3 URLs?"""

    type: Literal["S3_COMPATIBLE"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


class OriginListResponseItemCloudinaryBackup(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    bucket: str
    """S3 bucket name."""

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    prefix: object
    """Path prefix inside the bucket."""

    type: Literal["CLOUDINARY_BACKUP"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


class OriginListResponseItemWebFolder(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    base_url: object = FieldInfo(alias="baseUrl")
    """Root URL for the web folder origin."""

    forward_host_header_to_origin: bool = FieldInfo(alias="forwardHostHeaderToOrigin")
    """Forward the Host header to origin?"""

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    type: Literal["WEB_FOLDER"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


class OriginListResponseItemWebProxy(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    type: Literal["WEB_PROXY"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


class OriginListResponseItemGoogleCloudStorageGcs(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    bucket: str

    client_email: str = FieldInfo(alias="clientEmail")

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    prefix: object

    type: Literal["GCS"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


class OriginListResponseItemAzureBlobStorage(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    account_name: str = FieldInfo(alias="accountName")

    container: str

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    prefix: object

    type: Literal["AZURE_BLOB"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


class OriginListResponseItemAkeneoPim(BaseModel):
    id: str
    """Unique identifier for the origin.

    This is generated by ImageKit when you create a new origin.
    """

    base_url: object = FieldInfo(alias="baseUrl")
    """Akeneo instance base URL."""

    include_canonical_header: bool = FieldInfo(alias="includeCanonicalHeader")
    """Whether to send a Canonical header."""

    name: str
    """Display name of the origin."""

    type: Literal["AKENEO_PIM"]

    base_url_for_canonical_header: Optional[str] = FieldInfo(alias="baseUrlForCanonicalHeader", default=None)
    """URL used in the Canonical header (if enabled)."""


OriginListResponseItem: TypeAlias = Union[
    OriginListResponseItemS3,
    OriginListResponseItemS3Compatible,
    OriginListResponseItemCloudinaryBackup,
    OriginListResponseItemWebFolder,
    OriginListResponseItemWebProxy,
    OriginListResponseItemGoogleCloudStorageGcs,
    OriginListResponseItemAzureBlobStorage,
    OriginListResponseItemAkeneoPim,
]

OriginListResponse: TypeAlias = List[OriginListResponseItem]
