#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."



export DEFER_PYDANTIC_BUILD=false

echo "==> Running tests"
rye run pytest "$@"

echo "==> Running Pydantic v1 tests"
rye run nox -s test-pydantic-v1 -- "$@"
