import enum


class Default(enum.Enum):
    DEFAULT_TRANSFORMATION_POSITION = "path"
    QUERY_TRANSFORMATION_POSITION = "query"
    VALID_TRANSFORMATION_POSITION = [
        DEFAULT_TRANSFORMATION_POSITION,
        QUERY_TRANSFORMATION_POSITION,
    ]
    DEFAULT_TIMESTAMP = "9999999999"
    SDK_VERSION = "python-2.2.4"
